name: "dbt_starter_project" # De naam van het project
version: "1.0"
config-version: 2

profile: "default" # De profielnaam die wordt gebruikt om verbinding te maken met de database

models:
  dbt-starter-project: # Dit moet exact overeenkomen met de projectnaam hierboven
    +catalog: hive_metastore # Standaard catalogus voor alle modellen
    +schema: default # Standaard schema voor alle modellen

    mart:
      +materialized: incremental # Alleen dit model wordt als een fysieke tabel opgeslagen (voor gebruik in Power BI)

    intermediate:
      +materialized: view # Modellen in deze map worden als views opgeslagen omdat ze tijdelijke transformaties bevatten

    staging:
      +materialized: view # Alle staging-modellen worden als view opgeslagen
